### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by andermarce** [cameronfr/IrreversibleTokenStreaming#2]
When I open localhost url  appear this error and blank page.
![Captura de tela de 2021-04-10 21-38-28](https://user-images.githubusercontent.com/824218/114288326-2e96fc80-9a45-11eb-86fa-dafec9ad8b7f.png)

**Comment by cameronfr** [comment]
Looks like you’re running untransformed code; running 

yarn global add parcel-bundler 

and then 

parcel watch index.html

should serve the site on localhost

**Comment by andermarce** [comment]
Hi @cameronfr thanks for answer;. I try to run this instructions but see above:

![Captura de tela de 2021-04-10 21-57-52](https://user-images.githubusercontent.com/824218/114288605-ee854900-9a47-11eb-8ea7-25bd10cdaa3a.png)
![Captura de tela de 2021-04-10 21-59-09](https://user-images.githubusercontent.com/824218/114288616-00ff8280-9a48-11eb-8df1-9ce597b2828c.png)

**Comment by andermarce** [comment]
Hey @cameronfr 

I tried to run only with: parcel index.html
Now it's work!

Thank you
![Captura de tela de 2021-04-10 22-09-47](https://user-images.githubusercontent.com/824218/114288900-b4b54200-9a49-11eb-991f-d973a4234f4d.png)
![Captura de tela de 2021-04-10 22-09-56](https://user-images.githubusercontent.com/824218/114288902-b67f0580-9a49-11eb-85a9-1b64a8619421.png)
